### ISSUE TITLE
Not able to run in strict mode

### ISSUE THREAD

**Issue by sk22** [EDMdesigner/textversionjs#1]
In strict mode (`node --use_strict`), the following code creates a TypeError.

```
const textVersion = require('textversionjs')
```

```
TypeError: Cannot read property 'define' of undefined
    at C:\Users\samuel\Code\node\telegram\openshift-dev\node_modules\textversionjs\src\textversion.js:176:17
    at Object.<anonymous> (C:\Users\samuel\Code\node\telegram\openshift-dev\node_modules\textversionjs\src\textversion.js:190:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at repl:1:21
```

while executing the same code without `--use_strict` works just fine.
### Versions:

```
node v6.3.1
npm v3.10.3
textversionjs v1.0.0
```

running on Windows 10

**Comment by gyulanemeth** [comment]
Hello, thank you for reporting this, we will fix it tomorrow.

**Comment by stubendek** [comment]
Hi, we fixed the issue, please confirm back if it works.

**Comment by gyulanemeth** [comment]
I consider it as solved.
